# Misc
homepage:
    pattern: /{page}
    defaults: { _controller: LandmarxCoreBundle:Homepage:index, page: 1 }
    requirements:
        page: \d+
        
about:
    pattern: /about
    defaults: { _controller: LandmarxCoreBundle:Homepage:about }

contact:
    pattern: /contact
    defaults: { _controller: LandmarxCoreBundle:Homepage:contact }

# FOS
fos_user_security_login:
    pattern: /signin
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    pattern: /signin-check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    pattern: /signout
    defaults: { _controller: FOSUserBundle:Security_logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /signup

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Imagine
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
# User Bundle
landmarx_user:
    resource: "@LandmarxUserBundle/Resources/config/routing/user.yml"
    prefix: /users
    
# Landmark Bundle
landmarx_landmark:
    resource: "@LandmarxLandmarkBundle/Resources/config/routing/landmark.yml"
    prefix: /landmarks
    